BINARY := bookpi
VERSION ?= vlatest

all: help

.PHONY: help
help:
	@echo
	@echo "List of commands:"
	@echo
	@echo "  make help	      - display this message"
	@echo "  make dist        - create a tarball of all necessary files"
	@echo "  make deps	      - get dependencies for all projects"
	@echo "  make deps-go     - add dependencies for the server"
	@echo "  make deps-js     - add dependencies for the frontend"
	@echo "  make deps-py     - add dependencies for the display"
	@echo "  make build	      - build all projects"
	@echo "  make build-go    - build the server binary"
	@echo "  make build-js    - build the frontend"
	@echo "  make build-py    - build the display binary"
	@echo "  make clean	      - clean all projects"
	@echo "  make clean-dist  - remove files for distribution"
	@echo "  make clean-go    - remove all files generated by the server"
	@echo "  make clean-js    - remove generated js files"
	@echo "  make clean-py    - remove generated py files"

.PHONY: dist
dist: clean-dist deps build
	mkdir -p bookpi
	cp releases/* bookpi/
	cp services/* bookpi/
	cp install.sh bookpi/
	cp bookpi.sh bookpi/
	tar caf bookpi.tar.gz bookpi/*

# Dependencies
.PHONY: deps
deps: deps-go deps-js deps-py

.PHONY: deps-go
deps-go:
	$(MAKE) -C server deps

.PHONY: deps-js
deps-js:
	$(MAKE) -C frontend deps

.PHONY: deps-py
deps-py:
	$(MAKE) -C display deps

# Building
.PHONY: build
build: build-js build-go build-py

.PHONY: build-go
build-go: build-js deps-go
	rm -rf server/build
	mv frontend/build server
	$(MAKE) -C server build
	mkdir -p releases
	mv server/server releases/$(BINARY)-$(VERSION)-server

.PHONY: build-js
build-js: deps-js
	$(MAKE) -C frontend build

.PHONY: build-py
build-py:
	$(MAKE) -C display build
	mkdir -p releases
	mv display/dist/main releases/$(BINARY)-$(VERSION)-display

# Cleaning
.PHONY: clean
clean: clean-go clean-js clean-py clean-dist

.PHONY: clean-dist
clean-dist:
	rm -rf releases
	rm -rf bookpi
	rm -rf bookpi.tar.gz

.PHONY: clean-go
clean-go:
	$(MAKE) -C server clean

.PHONY: clean-js
clean-js:
	$(MAKE) -C frontend clean

.PHONY: clean-py
clean-py:
	$(MAKE) -C display clean
